services:
  # A Docker web service
  - type: web
    name: Ngrok
    env: docker
    repo: https://github.com/craxid/rairu-kun # optional
    region: Singapore # optional (defaults to Singapore)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: 8080 # ngrok port
        value: 22
      - key: 1jBaIkPQugi74kCjlqX5RwruIMk_3PivvuKGD19kzDc1qxYNW # ngrok token
        sync: false
      - key: REGION # ngrok region
        sync: false
